### PR TITLE
Options can now be set to a proc

### PR DESCRIPTION
**Pull request by gja**

### CODE REVIEW

**Comment by cymen** [comment]
@gja This looks good to me. I'll merge this in. Thanks for adding a test.

Can I ask how you plan on using this and if you need it ASAP? If so, I can merge, bump version and get a new gem created.

**Comment by gja** [comment]
I'm actually using rails to build multiple assets from the same JS code, and different template directories. See github.com/joeybaker/remapify/pull/37

**Comment by cymen** [comment]
Ah! Interesting

**Comment by cymen** [comment]
@gja I released 0.9.1 w/ your change

**Comment by gja** [comment]
Thanks.

**Comment by cymen** [comment]
@gja Are you using this feature? @cqql merged a change here https://github.com/browserify-rails/browserify-rails/commit/53dcf0393ace695334d539ef009c3028ec338574 to fix an error. I noticed that error too but was addressing it on https://github.com/browserify-rails/browserify-rails/tree/make_dependencies_more_flexibile . CI went red but I also wondered if this feature still works on current master.

**Pull request merged**
