### PR TITLE
Update Readme

### LINKED ISSUE #167: Rails Engine?
I'm trying to use the browserify with a Rails engine.

I followed the Getting Started but I'm geting the error `Uncaught ReferenceError: require is not defined`.

Any tip?

Thanks =)

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
Added example of including an external node module.
Added more specific instructions to engine section.

Closes #167

### CODE REVIEW

**Comment by cymen** [comment]
Thanks!

**Comment by cymen** [comment]
I released 3.4.0 with your change. Thanks again.

**Comment by cymen** [comment]
Oh, I missed this was on a branch. Sorry, still drinking coffee. This is not in 3.4.0 -- is it ready for master? If so, we can merge it in and push it out. If not ready yet, no problem.

**Comment by valentin-krasontovitsch** [comment]
That's quite alright : )

So I'm a bit shaky on the modules and require
concepts, just getting started with that, so I'm
still not sure about how to actually include an
external module properly.

Just made a separate script with a require
statement and then include that script in my
other scripts whenever I need that library...
Maybe this is something worth adding to the
Readme still, but I'm not ready to do it yet : )

Besides that, I think it can be merged.

**Pull request merged**
